###############################################################################
###############################################################################

# Program: Supplementary_Table_15.py
# Author: Sergio Cámara Peña
# Date: 21/07/2026
# Version: FINAL
# Additional info: Check "PyDESeq2_CD8_clusters.py", "PyDESeq2_IACs_clusters.py", "Dreamlet_CD8_clusters.R", and "Dreamlet_IACs_clusters.R" scripts
# Machine: Rocinante

###############################################################################
###############################################################################

# %% Command-line and environment path configuration

import argparse
import os
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent if "__file__" in globals() else Path.cwd()
_ARTICLE_DIR = next(
    (candidate for candidate in (_SCRIPT_DIR, *_SCRIPT_DIR.parents) if candidate.name == "Article"),
    _SCRIPT_DIR / "Article" if (_SCRIPT_DIR / "Article").is_dir() else _SCRIPT_DIR,
)
_path_parser = argparse.ArgumentParser()
_path_parser.add_argument(
    "--project-dir",
    default=os.environ.get("CART_ATLAS_PROJECT_DIR", str(_ARTICLE_DIR)),
    help="Root containing the repository-relative data, results, figure, model, and metadata subdirectories.",
)
_path_args, _unknown_path_args = _path_parser.parse_known_args()
project_dir = Path(_path_args.project_dir).expanduser().resolve()
if not project_dir.is_dir():
    raise FileNotFoundError(
        f"Project directory does not exist: {project_dir}. "
        "Set --project-dir or CART_ATLAS_PROJECT_DIR."
    )


# %% Import libraries
import os
import pandas as pd


# %% Results directory
results_dir = project_dir / "Resultados" / "Dreamlet_Vs_PyDESeq2"
input_dir = project_dir / "Input"


# %% CSV files generated by the four Dreamlet/PyDESeq2 scripts
csv_files = [
    # CD8 comparison 1
    "Dreamlet_de_genes_CD8_Comparison_1.csv",
    "PyDESeq2_de_genes_CD8_Comparison_1.csv",
    "PyDESeq2_Dreamlet_CD8_comparison_1_summary.csv",

    # CD8 comparison 2
    "Dreamlet_de_genes_CD8_Comparison_2.csv",
    "PyDESeq2_de_genes_CD8_Comparison_2.csv",
    "PyDESeq2_Dreamlet_CD8_comparison_2_summary.csv",

    # CD8 comparison 3
    "Dreamlet_de_genes_CD8_Comparison_3.csv",
    "PyDESeq2_de_genes_CD8_Comparison_3.csv",
    "PyDESeq2_Dreamlet_CD8_comparison_3_summary.csv",

    # IACs comparison
    "Dreamlet_de_genes_IACs_clusters.csv",
    "PyDESeq2_de_genes_IACs_clusters.csv",
    "PyDESeq2_Dreamlet_IACs_clusters_comparison_summary.csv",
]


# %% Configure pandas printing
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)


# %% Check input directories
if not results_dir.is_dir() and not input_dir.is_dir():
    raise FileNotFoundError(
        "Neither generated-input directory exists. Checked:\n"
        f"{results_dir}\n{input_dir}"
    )


# %% Read and print every CSV
missing_files = []
failed_files = []

for csv_name in csv_files:

    csv_path = results_dir / csv_name
    if not csv_path.is_file():
        alternate_csv_path = input_dir / csv_name
        if alternate_csv_path.is_file():
            csv_path = alternate_csv_path
    print("\n")
    print("=" * 120)
    print(f"FILE: {csv_name}")
    print("=" * 120)
    if not csv_path.is_file():
        print(f"FILE NOT FOUND: {csv_path}")
        missing_files.append(csv_name)
        continue
    try:
        df = pd.read_csv(csv_path)

        # CSVs written with row names/index usually contain an
        # unnamed first column. Rename it to Gene for readability.
        if (
            len(df.columns) > 0
            and str(df.columns[0]).startswith("Unnamed:")
        ):
            df = df.rename(columns={df.columns[0]: "Gene"})

        print(
            f"Dimensions: {df.shape[0]} rows x "
            f"{df.shape[1]} columns\n"
        )

        print(df.to_string(index=False))

    except Exception as error:
        print(f"ERROR READING FILE: {error}")
        failed_files.append(csv_name)

# %% End of script
